name: management_rack
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  pdf: ^3.10.6
  printing: ^5.11.1
  path_provider: ^2.1.2
  provider: ^6.1.1
  intl: ^0.19.0
  uuid: ^4.3.3
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo1.png